<div class="relative" data-language-menu data-locale="{{ app()->getLocale() }}">
    <button type="button" data-language-trigger class="ui-action inline-flex h-10 items-center gap-2 rounded-lg border border-neutral-300 bg-white px-3 text-sm font-semibold text-neutral-700 shadow-sm outline-none transition hover:border-neutral-400 hover:bg-neutral-50 focus:border-neutral-500 focus:ring-4 focus:ring-neutral-500/10 dark:border-white/20 dark:bg-white/[0.06] dark:text-neutral-200 dark:hover:border-white/30 dark:hover:bg-white/10" aria-haspopup="menu" aria-expanded="false">
        <svg class="size-4 text-neutral-500 dark:text-neutral-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.2 2.4 3.3 5.4 3.3 9s-1.1 6.6-3.3 9c-2.2-2.4-3.3-6.6-3.3-9S9.8 5.4 12 3Z"/></svg>
        <span data-language-label>{{ app()->getLocale() === 'vi' ? 'Tiếng Việt' : 'English' }}</span>
        <svg class="size-4 text-neutral-400 transition-transform" data-language-chevron viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
    </button>
    <div data-language-options hidden class="absolute right-0 top-[calc(100%+0.5rem)] z-50 w-44 origin-top-right rounded-xl border border-neutral-200 bg-white p-1.5 shadow-xl shadow-neutral-900/10 dark:border-white/15 dark:bg-neutral-900 dark:shadow-black/30" role="menu" aria-label="{{ __('ui.app.language') }}">
        <button type="button" data-language-option data-locale="vi" class="ui-action flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm font-medium text-neutral-700 transition hover:bg-neutral-100 hover:text-neutral-950 focus:bg-neutral-100 focus:outline-none dark:text-neutral-200 dark:hover:bg-white/10 dark:hover:text-white dark:focus:bg-white/10" role="menuitem">Tiếng Việt <span data-language-check class="hidden text-emerald-600 dark:text-emerald-400">✓</span></button>
        <button type="button" data-language-option data-locale="en" class="ui-action flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm font-medium text-neutral-700 transition hover:bg-neutral-100 hover:text-neutral-950 focus:bg-neutral-100 focus:outline-none dark:text-neutral-200 dark:hover:bg-white/10 dark:hover:text-white dark:focus:bg-white/10" role="menuitem">English <span data-language-check class="text-emerald-600 dark:text-emerald-400">✓</span></button>
    </div>
</div>
