<?php

return [
    'public_login_on_continue' => 'Select your seats first. You will sign in only when you continue to hold them.',
    'public' => ['movies' => 'Movies', 'showtimes' => 'Showtimes', 'menu_title' => 'Explore', 'menu' => ['movies' => 'Movies', 'movies_description' => 'Browse movies and showtimes.'], 'my_account' => 'My account', 'login' => 'Sign in', 'footer' => 'Your seat is waiting.', 'eyebrow' => 'Movie nights, made easy', 'hero_title' => 'Your next great story starts here.', 'hero_description' => 'Browse movies, choose a showtime and pick your seats before you arrive.', 'now_showing' => 'Now showing', 'choose_movie' => 'Find your movie', 'view_showtimes' => 'View showtimes', 'movie_details' => 'Movie details', 'no_synopsis' => 'A new story is waiting on the big screen.', 'select_showtime' => 'Select a showtime', 'choose_seats' => 'Choose seats', 'continue' => 'Continue to booking', 'seats_available' => ':available of :total seats available', 'seats_summary' => 'Seats: :available available / :total total', 'hold_expired' => 'Expired holds are available again.'],
    'screenings' => ['title' => 'Now showing', 'description' => 'Choose a movie, showtime and your seats.', 'empty' => 'No screenings are available.', 'choose_seats' => 'Choose seats'],
    'seats' => ['screen' => 'Screen', 'available' => 'Available', 'unavailable' => 'Unavailable', 'selected' => 'Selected', 'selected_count' => 'seat(s) selected', 'hold' => 'Hold selected seats'],
    'tickets' => ['title' => 'Tickets', 'verify' => 'Ticket verification', 'qr_payload' => 'Secure ticket link', 'qr_hint' => 'This signed QR code is valid for 24 hours.'],
    'reports' => ['title' => 'Cinema reports', 'description' => 'Current-month orders, ticket usage and money movement.', 'orders' => 'Orders', 'tickets' => 'Tickets', 'checked_in' => 'Checked in', 'revenue' => 'Revenue (minor)', 'refunded' => 'Refunded (minor)'],
    'check_in' => ['ticket_code' => 'Ticket code', 'submit' => 'Check in'],
    'admin' => ['title' => 'Cinema management', 'description' => 'Manage movies, rooms, seats and showtimes.', 'add_movie' => 'Add movie', 'add_room' => 'Add screening room', 'add_screening' => 'Add screening', 'movie_title' => 'Movie title', 'duration' => 'Duration (minutes)', 'synopsis' => 'Synopsis', 'room_name' => 'Room name', 'room_code' => 'Room code', 'rows' => 'Rows (comma separated)', 'seats_per_row' => 'Seats per row', 'movie' => 'Movie', 'room' => 'Room', 'starts_at' => 'Starts at', 'ends_at' => 'Ends at', 'price' => 'Base price (minor)', 'currency' => 'Currency', 'upcoming' => 'Upcoming screenings', 'movie_created' => 'Movie created.', 'room_created' => 'Room and seats created.', 'screening_created' => 'Screening and seat inventory created.'],
];
