<x-layouts.storefront :title="$screening->movie->title">
    <div class="mx-auto max-w-5xl space-y-8 px-5 py-12 sm:px-8" data-seat-picker>
        <div>
            <a href="{{ route('cinema.movies.show', $screening->movie) }}" class="text-sm font-semibold text-primary hover:underline">← {{ $screening->movie->title }}</a>
            <h1 class="mt-3 text-3xl font-semibold">{{ __('cinema.public.choose_seats') }}</h1>
            <p class="mt-2 text-sm text-muted-foreground">{{ $screening->room->name }} · {{ $screening->starts_at->timezone($screening->room->timezone)->format('D, d/m/Y · H:i') }}–{{ $screening->ends_at->timezone($screening->room->timezone)->format('H:i') }}</p>
            <div class="mt-4 inline-flex rounded-full bg-primary-soft px-4 py-2 text-sm font-semibold text-accent-foreground">{{ __('cinema.public.seats_summary', $seatSummary) }}</div>
        </div>
        <x-auth.feedback />
        @error('seat_ids')<p class="rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{{ $message }}</p>@enderror
        @guest<p class="rounded-xl border border-primary/20 bg-primary-soft/50 p-4 text-sm text-accent-foreground">{{ __('cinema.public_login_on_continue') }}</p>@endguest
        <form method="POST" action="{{ route('cinema.screenings.hold', $screening) }}" class="space-y-6">
            @csrf<input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', (string) Str::uuid()) }}">
            <section class="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-8"><div class="mx-auto mb-8 max-w-md rounded-full bg-slate-900 py-2 text-center text-xs font-semibold uppercase tracking-[.2em] text-white">{{ __('cinema.seats.screen') }}</div><div class="mx-auto grid max-w-2xl gap-3">@foreach($screening->screeningSeats->groupBy(fn($item) => $item->seat->row_label) as $row => $seats)<div class="flex items-center gap-3"><span class="w-6 text-center text-xs font-bold text-muted-foreground">{{ $row }}</span><div class="grid flex-1 gap-2" style="grid-template-columns:repeat({{ min(12, max(1, $seats->count())) }},minmax(0,1fr));">@foreach($seats as $screeningSeat)@php($available=$screeningSeat->isAvailableForSelection())<button type="button" data-seat-id="{{ $screeningSeat->seat_id }}" @disabled(!$available) class="aspect-square rounded-lg border text-xs font-bold transition {{ $available?'border-border bg-background hover:border-primary hover:bg-primary/10':'cursor-not-allowed border-border bg-muted text-muted-foreground line-through' }}" title="{{ $screeningSeat->seat->row_label }}{{ $screeningSeat->seat->seat_number }}">{{ $screeningSeat->seat->seat_number }}</button>@endforeach</div></div>@endforeach</div><div class="mt-8 flex justify-center gap-4 text-xs text-muted-foreground"><span>● {{ __('cinema.seats.available') }}</span><span class="text-primary">● {{ __('cinema.seats.selected') }}</span></div></section>
            <section class="flex flex-col items-center justify-between gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm sm:flex-row"><p class="text-sm text-muted-foreground"><span data-seat-count>0</span> {{ __('cinema.seats.selected_count') }}</p><x-admin.button type="submit" icon="arrow-right" data-seat-submit disabled>{{ __('cinema.public.continue') }}</x-admin.button></section>
        </form>
    </div>
    <script>document.querySelectorAll('[data-seat-picker]').forEach((picker)=>{const form=picker.querySelector('form'),buttons=picker.querySelectorAll('[data-seat-id]'),count=picker.querySelector('[data-seat-count]'),submit=picker.querySelector('[data-seat-submit]');const sync=()=>{picker.querySelectorAll('[data-seat-input]').forEach((input)=>input.remove());const selected=[...buttons].filter((button)=>button.dataset.selected==='true');selected.forEach((button)=>{const input=document.createElement('input');input.type='hidden';input.name='seat_ids[]';input.value=button.dataset.seatId;input.dataset.seatInput='';form.append(input)});count.textContent=selected.length;submit.disabled=!selected.length};buttons.forEach((button)=>button.addEventListener('click',()=>{button.dataset.selected=button.dataset.selected==='true'?'false':'true';button.classList.toggle('border-primary',button.dataset.selected==='true');button.classList.toggle('bg-primary/10',button.dataset.selected==='true');sync()}))});</script>
</x-layouts.storefront>
