<x-layouts.auth :title="__('cinema.admin.title')" :heading="__('cinema.admin.title')">
    <div class="space-y-6">
        <x-admin.page-header :title="__('cinema.admin.title')" :description="__('cinema.admin.description')" />
        @if (session('status')) <x-admin.toast :message="__(session('status'))" /> @endif
        <div class="grid gap-6 lg:grid-cols-3">
            <form method="POST" action="{{ route('admin.cinema.movies.store') }}" class="space-y-4 rounded-2xl border border-border bg-card p-5">@csrf<h2 class="font-semibold">{{ __('cinema.admin.add_movie') }}</h2><x-auth.input :label="__('cinema.admin.movie_title')" name="title" required /><x-auth.input :label="__('cinema.admin.duration')" name="duration_minutes" type="number" min="1" required /><x-auth.textarea :label="__('cinema.admin.synopsis')" name="synopsis" rows="3" /><x-admin.button type="submit" icon="plus">{{ __('ui.actions.create') }}</x-admin.button></form>
            <form method="POST" action="{{ route('admin.cinema.rooms.store') }}" class="space-y-4 rounded-2xl border border-border bg-card p-5">@csrf<h2 class="font-semibold">{{ __('cinema.admin.add_room') }}</h2><x-auth.input :label="__('cinema.admin.room_name')" name="name" required /><x-auth.input :label="__('cinema.admin.room_code')" name="code" required /><x-auth.input :label="__('booking.admin.timezone')" name="timezone" value="Asia/Ho_Chi_Minh" required /><x-auth.input :label="__('cinema.admin.rows')" name="rows" value="A,B,C,D,E,F" required /><x-auth.input :label="__('cinema.admin.seats_per_row')" name="seats_per_row" type="number" value="10" min="1" max="50" required /><x-admin.button type="submit" icon="plus">{{ __('ui.actions.create') }}</x-admin.button></form>
            <form method="POST" action="{{ route('admin.cinema.screenings.store') }}" class="space-y-4 rounded-2xl border border-border bg-card p-5">@csrf<h2 class="font-semibold">{{ __('cinema.admin.add_screening') }}</h2><label class="block text-sm font-medium">{{ __('cinema.admin.movie') }}<select name="movie_id" class="mt-1 w-full rounded-md border border-input bg-card px-3 py-2 text-sm" required>@foreach ($movies as $movie)<option value="{{ $movie->id }}">{{ $movie->title }}</option>@endforeach</select></label><label class="block text-sm font-medium">{{ __('cinema.admin.room') }}<select name="screening_room_id" class="mt-1 w-full rounded-md border border-input bg-card px-3 py-2 text-sm" required>@foreach ($rooms as $room)<option value="{{ $room->id }}">{{ $room->name }}</option>@endforeach</select></label><x-auth.input :label="__('cinema.admin.starts_at')" name="starts_at" type="datetime-local" required /><x-auth.input :label="__('cinema.admin.ends_at')" name="ends_at" type="datetime-local" required /><div class="grid grid-cols-2 gap-3"><x-auth.input :label="__('cinema.admin.price')" name="base_price_minor_units" type="number" min="0" required /><x-auth.input :label="__('cinema.admin.currency')" name="currency" value="VND" maxlength="3" required /></div><x-admin.button type="submit" icon="plus">{{ __('ui.actions.create') }}</x-admin.button></form>
        </div>
        <section class="rounded-2xl border border-border bg-card p-5"><h2 class="font-semibold">{{ __('cinema.admin.upcoming') }}</h2><div class="mt-4 divide-y divide-border">@foreach ($screenings as $screening)<div class="flex flex-col justify-between gap-1 py-3 text-sm sm:flex-row"><span class="font-medium">{{ $screening->movie?->title }} · {{ $screening->room?->name }}</span><span class="text-muted-foreground">{{ $screening->starts_at->format('d/m/Y H:i') }}–{{ $screening->ends_at->format('H:i') }}</span></div>@endforeach</div>{{ $screenings->links() }}</section>
    </div>
</x-layouts.auth>
